#!/usr/bin/env node

var app = require("./backend/app");

app.listen(process.env.PORT || 3000, function() {
	var address = this.address();
	console.log("→ http://%s:%d", address.address, address.port);
});
